; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; ESP32-S3-Mini-1-N4R2: 4MB flash, 2MB PSRAM; the default board assumes 8MB/no PSRAM
board_build.flash_size = 4MB
board_build.partitions = default.csv
board_build.arduino.memory_type = qio_opi
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -Iextern/scpi-parser/libscpi/inc
    -DHAVE_STRNLEN=1
    -DHAVE_STRNCASECMP=1
    -DHAVE_SNPRINTF=1
    -DHAVE_STRTOF=1
    -DHAVE_ISNAN=1
    -DHAVE_ISFINITE=1
    -DHAVE_SIGNBIT=1
    -DHAVE_STRTOLL=1
lib_deps =
    olikraus/U8g2
    robtillaart/RunningAverage
    scpi-parser
